namespace LitteCmsNet
{
	public enum LcmsRenderingIntent : uint
	{
		// ICC Intents
		PERCEPTUAL = 0,
		RELATIVE_COLORIMETRIC = 1,
		SATURATION = 2,
		ABSOLUTE_COLORIMETRIC = 3,

		// Non-ICC intents
		PRESERVE_K_ONLY_PERCEPTUAL = 10,
		PRESERVE_K_ONLY_RELATIVE_COLORIMETRIC = 11,
		PRESERVE_K_ONLY_SATURATION = 12,
		PRESERVE_K_PLANE_PERCEPTUAL = 13,
		PRESERVE_K_PLANE_RELATIVE_COLORIMETRIC = 14,
		PRESERVE_K_PLANE_SATURATION = 15

	}
}
